# Generated by Django 5.2.18 on 2026-10-09 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sensorreading',
            new_name='monitoring__device__01464c_idx',
            old_name='monitoring_device__b4b966_idx',
        ),
    ]
